name: Commit to Other Repo

on:
  workflow_dispatch:
  
jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the source repository
      uses: actions/checkout@v2
        
    - name: Checkout the target repository
      uses: actions/checkout@v2
      with:
        repository: Night-stars-1/test1
        token: ${{ secrets.GAYHUB_TOKEN }} 
        path: target-repo
        
    - name: Make changes
      run: |
        RANDOM_NUMBER=$RANDOM
        echo "New content with random number: $RANDOM_NUMBER" > target-repo/new-file.txt

    - name: Commit and push changes to the target repository
      uses: EndBug/add-and-commit@v9.1.4
      with:
        default_author: github_actions
        message: "Commit from GitHub Actions"
        cwd: "target-repo"
